new Vue({
	el: '#vue-app',
	data: {
        name: 'Adam Pierce',
        address: 'Dallas',
        phone: '9908736531',
        email: 'adam@gmail.com',
        date:'1998-01-01',
        obj1:'Enter Your Objective. Can only write 250 Characters',        
        schoolname:'School Name',
        schoolocation:'Location',
        schooldegree:'Degree',
        schoolboard:'Board',
        schoolscore:'Percentage',        
        hschoolname:'High School',
        hschoolocation:'Location',
        hschooldegree:'Degree',
        hschoolboard:'Board',
        hschoolscore:'Percentage',
        smonth1:'Month',
        syear1:'Year',
        emonth1:'Month',
        eyear1:'Year',
        smonth2:'Month',
        syear2:'Year',
        emonth2:'Month',
        eyear2:'Year',
        smonth3:'Month',
        syear3:'Year',
        emonth3:'Month',
        eyear3:'Year',
        collegename:'Collage Name',
        collegelocation:'Location',
        collegedegree:'Degree',
        collegescore:'Percentage',
        mcollegename:'Collage Name',
        mcollegelocation:'Location',
        mcollegedegree:'Degree',
        mcollegescore:'Percentage',
        msmonth:'Month',
        msyear:'Year',
        memonth:'Month',
        meyear:'Year',
        pr1:'Project Name',
        pr2:'Project Name',
        pro1:'Add Description. Can only write in 150 Characters',
        pro2:'Add Description. Can only write in 150 Characters',
        tr1:'Company Name',
        tr2:'Company Name',        
        tra1:'Add Description. Can only write in 150 Characters',
        tra2:'Add Description. Can only write in 150 Characters',        
        tsdate1:'Month',
        tedate1:'Year',
        tsdate2:'Month',
        tedate2:'Year',
        tsdate3:'Month',
        tedate3:'Year',
        tsdate4:'Month',
        tedate4:'Year',
        psdate1:'Month',
        pedate1:'Year',
        psdate2:'Month',
        pedate2:'Year',
        psdate3:'Month',
        pedate3:'Year',
        psdate4:'Month',
        pedate4:'Year',
        ski1:'Skill 1',
        ski2:'Skill 2',
        ski3:'Skill 3',
        ski4:'Skill 4',
        ski5:'Skill 5',
        ski6:'Skill 6',
        ach1:'Achievements 1',
        ach2:'Achievements 2',
        ach3:'Achievements 3',
        seen: false,
        seen2: false,
        seen3: false
	},
	methods: {
		
		
	}
});

